config/routes.rb
Rails.application.routes.draw do

  resources :rentables

  resources :rentable

  resources :location

  get '/search', to: 'rentables#search'
  post '/search', to: 'rentables#search'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root 'welcome#index'
  get 'welcome/index'

end

app/models/rentable.rb
class Rentable < ActiveRecord::Base
  geocoded_by :address  # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [ :facebook ]

 def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.name = auth.info.name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rentables_controller.rb
class RentablesController < ApplicationController
  before_action :set_rentable, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
      @rentables = Rentable.all
      @hash = Gmaps4rails.build_markers(@rentables) do |rentable, marker|
        marker.lat rentable.latitude
        marker.lng rentable.longitude
      end
  end

  def show
    respond_with(@rentable)
  end

  def search
    @rentable = Rentable.new
    Rentable.near(@rentable_params, 1)
    respond_with(@rentable)
  end

  # WTF?


  def new
    @rentable = Rentable.new
    respond_with(@rentable)
  end

  def edit
  end

  def create
    @rentable = Rentable.new(rentable_params)
    @rentable.save
    respond_with(@rentable)
  end

  def update
    @rentable.update(rentable_params)
    respond_with(@rentable)
  end

  def destroy
    @rentable.destroy
    respond_with(@rentable)
  end

  private
    def set_rentable
      @rentable = Rentable.find(params[:id])
    end

    def rentable_params
      params.require(:rentable).permit(:latitude, :longitude, :address, :description, :title, :price, :picture)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

    def index
        @rentables = Rentable.all
        @hash = Gmaps4rails.build_markers(@rentables) do |rentable, marker|
          marker.lat rentable.latitude
          marker.lng rentable.longitude
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rentables_helper.rb
module RentablesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>La gaufriere</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag "application" %>


     <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Raleway">

     <%= javascript_include_tag "https://maps.google.com/maps/api/js?sensor=false" %>
     <%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>

     <%= javascript_include_tag "application" %>


     <%= yield(:js) %>

</head>

<body>

  <%=render 'shared/navbar' %>

  <div class="main">
    <div class="container tim-container" style="max-width:1500px; padding-top:100px">

  <%= yield %>

  <br>


<!--   intégration temporaire gmaps -->


<!-- fin -->

<!-- #peut-être à virer -->

    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

<!--   #fin -->

  </div>
    <div class="space-100"></div>
    <br>
    <div class="space-100"></div>
    <p class="text-center"><a href="https://www.facebook.com/florossini">Florian Rossini</a> &copy; 2014, I <i class="fa fa-heart"></i> my Kitchen !</p>

  </div>



</body>
</html>

app/views/rentables/_form.html.erb
<%= simple_form_for(@rentable, :html => {:multipart => true}) do |f| %>
<%= f.error_notification %>
<div class="form-inputs">
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :title %>
  <%= f.input :price %>
  <%= f.label :picture %>
  <%= f.file_field :picture %>

</div>

<br>

<div class="form-actions">

  <%= f.button :submit %>
</div>
<% end %>

app/views/rentables/edit.html.erb
<h1>Editing rentable</h1>

<%= render 'form' %>

<%= link_to 'Show', @rentable %> |
<%= link_to 'Back', rentables_path %>

app/views/rentables/index.html.erb
<!--

<table class='table'>
  <thead>
    <tr class="success">

      <th>Title</th>
      <th>Address</th>
      <th>Description</th>
      <th>Price</th>

      <th colspan="3"></th>
    </tr>
  </thead> -->

<br>

<div class="tablehover">

  <% @rentables.each do |rentable| %>
  <div class="test">

  <div class="floatinitial">
   <%= image_tag rentable.picture.url(:medium) %>

 </div>


 <div class="hiddenfloat">
  <p>
  <%= rentable.title %>  <br>
  <%= rentable.address %> <br>
  <%= rentable.description %> <br>
  <%= rentable.price %> <br> <br>
  <%= link_to 'Show', rentable %>
  <%= link_to 'Edit', edit_rentable_path(rentable) %>
  <%= link_to 'Destroy', rentable, method: :delete, data: { confirm: 'Are you sure?' }%>
  </p>
</div>

<!--  remplacer par une autre div... -->

</div>
<% end %>
</div>

app/views/rentables/new.html.erb
<h1>New rentable</h1>

<%= render 'form' %>

<%= link_to 'Back', rentables_path %>

app/views/rentables/search.html.erb
<%= simple_form_for(@rentable, :html => {:multipart => true}) do |f| %>
<%= f.error_notification %>
<div class="form-inputs">
  <%= f.input :address %>
</div>

<div class="form-actions">
<%= f.button :submit %>
</div>

<% end %>

app/views/rentables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @rentable.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @rentable.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @rentable.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @rentable.description %>
</p>

<p>
  <strong>Title:</strong>
  <%= @rentable.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @rentable.price %>
</p>


<%= link_to 'Edit', edit_rentable_path(@rentable) %> |
<%= link_to 'Back', rentables_path %>

app/views/shared/_navbar.html.erb
<div id="navbar-full">


  <div id="navbar">


       <!--
        navbar-default can be changed with navbar-ct-blue navbar-ct-azzure navbar-ct-red navbar-ct-green navbar-ct-orange
      -->
      <nav class="navbar navbar-ct-custom navbar-fixed-top navbar-transparent" role="navigation">

        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand navbar-brand-logo" href="http://http://www.la-gaufriere.com/">
              <div class="logo">
                <img src="http://img15.hostingpics.net/pics/874429resizedwaffle.png">
              </div>
              <div class="brand">La Gaufrière</div>

            </a>


          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li>
                <a href="welcome/index">
                  <i class="fa fa-home"></i>
                  <!--     <span class="label">0</span> -->
                </i>
                <p>Home</p>
              </a>
            </li>
            <li>
              <a href="/pages/contact">
                <i class="fa fa-envelope"></i>
                <!--     <span class="label">0</span> -->
              </i>

              <p>Contact</p>
              <!-- pourquoi quand je passe par ruby j'ai un espace entre l'envelope et le mot? -->
            </a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-question"></i>
              <p>About</p>
            </a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        </ul>



      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->

    <!--           facebook auth integration chercher dans mes mails-->


   <!-- end of facebook auth integration -->

 </nav>

 <div class="blurred-container">
  <div class="img-src background"></div>
</div>
</div>
</div><!--  end navbar -->

</div> <!-- end menu-dropdown -->

app/views/welcome/index.html.erb
<p>
  <div class="facebook">
      <% if user_signed_in? %>
      <%= image_tag current_user.picture, class: "img img-circle" %>
      <%= current_user.name %>
      <%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %>
      <% else %>
      <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
      <% end %>
    </div>

</p>




<h1 class="text-center">
 <b>
   La Gaufrière
   <br>
 </b>
 <small class="subtitle"><i>Préservez votre espace tout en bénéficiant d'un large choix d'ustensiles de cuisine à deux pas de chez vous...
 </i></small>
</h1>

<div class="container">
  <div class="map">

  <div id="map" style='width: 500px; height: 350px;'></div>
   </div>
   <script type="text/javascript">
   handler = Gmaps.build('Google');
   handler.buildMap({
    provider: {
      scrollwheel: false
    },
    internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
   </script>
  </div>
   <br>

   <h4 class="text-danger"><i>
   </i></h4>
   <div class="text center">
    <a href="/rentables/new" <button type="button" class="btn btn-warning btn-lg dropdown-toggle" role="button">
      Add your Object
    </a>

    <br> <br>

    <a href="/rentables" <button type="button" class="btn btn-danger btn-lg dropdown-toggle" role="button">
      Show all rentable objects
    </a>


</div>